
export let setupLinks = [];
export const sections = new Set();
const SETUP_ROOT = "/lightning/setup";

function add(sectionRoot, linkRoot, sectionLinks) {
  // Add links with section root title, common link root,
  // explicit true or false prod value
  // link.section value (if any) is appended to sectionRoot
  setupLinks.push(...sectionLinks
    .map(row => {
      const section = sectionRoot + (row.section || "");
      sections.add(section);
      const link = (linkRoot || "") + (row.link || "");
      const prod = !!row.prod;
      return {...row, section, link, prod};
    }));
}

// Setup
add("Setup", SETUP_ROOT, [
  {label: "Setup Home", link: "/SetupOneHome/home"},
  {label: "Service Setup Assistant", link: "/ServiceHome/home"},
  {label: "Service Setup", link: "/SetupOneHome/home"},
  {label: "Multi-Factor Authentication Assistant", link: "/MfaAssistant/home", alias: "MFA, multi factor, 2FA, two factor, 2 factor"},
  {label: "Release Updates", link: "/ReleaseUpdates/home"},
  {label: "Salesforce Mobile App", link: "/SalesforceMobileAppQuickStart/home"},
  {label: "Optimizer", link: "/SalesforceOptimizer/home"},
]);

//Administration > Users
add("Administration > Users", SETUP_ROOT, [
  {label: "Permission Sets Groups", link: "/PermSetGroups/home"},
  {label: "Permission Sets", link: "/PermSets/home"},
  {label: "Profiles", link: "/Profiles/home"},
  {label: "Profiles (Enhanced)", link: "/EnhancedProfiles/home"},
  {label: "Public Groups", link: "/PublicGroups/home"},
  {label: "Queues", link: "/Queues/home"},
  {label: "Roles", link: "/Roles/home"},
  {label: "User Management Settings", link: "/UserManagementSettings/home"},
  {label: "Users", link: "/ManageUsers/home"}
]);


add("Administration", SETUP_ROOT, [
  //Administration > Data
  {label: "Big Objects", link: "/BigObjects/home", section: " > Data"},
  {label: "Data Export", link: "/DataManagementExport/home", section: " > Data"},
  {label: "Data Integration Metrics", link: "/XCleanVitalsUi/home", section: " > Data"},
  {label: "Data Integration Rules", link: "/CleanRules/home", section: " > Data"},
  //Administration > Data > Duplicate Management
  {label: "Duplicate Error Logs", link: "/DuplicateErrorLog/home", section: " > Data > Duplicate Management"},
  {label: "Duplicate Rules", link: "/DuplicateRules/home", section: " > Data > Duplicate Management"},
  {label: "Matching Rules", link: "/MatchingRules/home", section: " > Data > Duplicate Management"},
  //Administration > Data
  {label: "Mass Delete Records", link: "/DataManagementDelete/home", section: " > Data"},
  {label: "Mass Transfer Approval Requests", link: "/DataManagementManageApprovals/home", section: " > Data"},
  {label: "Mass Transfer Records", link: "/DataManagementTransfer/home", section: " > Data"},
  {label: "Mass Update Addresses", link: "/DataManagementMassUpdateAddresses/home", section: " > Data"},
  {label: "Picklist Settings", link: "/PicklistSettings/home", section: " > Data"},
  {label: "Schema Settings", link: "/SchemaSettings/home", section: " > Data"},
  {label: "State and Country/Territory Picklists", link: "/AddressCleanerOverview/home", section: " > Data"},
  {label: "Storage Usage", link: "/CompanyResourceDisk/home", section: " > Data"},
  //Administration > Email
  {label: "Apex Exception Email", link: "/ApexExceptionEmail/home", section: " > Email"},
  {label: "Classic Email Templates", link: "/CommunicationTemplatesEmail/home", section: " > Email"},
  {label: "Compliance BCC Email", link: "/SecurityComplianceBcc/home", section: " > Email"},
  {label: "DKIM Keys", link: "/EmailDKIMList/home", section: " > Email"},
  {label: "Deliverability", link: "/OrgEmailSettings/home", section: " > Email"},
  {label: "Email Attachments", link: "/EmailAttachmentSettings/home", section: " > Email"},
  //Administration > Email > Delivery Settings
  {label: "Email Domain Filters", link: "/EmailDomainFilter/home", section: " > Email > Delivery Settings"},
  {label: "Email Relays", link: "/EmailRelay/home", section: " > Email > Delivery Settings"},
  //Administration >Email
  {label: "Email Footers", link: "/EmailDisclaimers/home", section: " > Email"},
  {label: "Email to Salesforce", link: "/EmailToSalesforce/home", section: " > Email"},
  {label: "Enhanced Email", link: "/EnhancedEmail/home", section: " > Email"},
  {label: "Gmail Integration and Sync", link: "/LightningForGmailAndSyncSettings/home", section: " > Email"},
  {label: "Letterheads", link: "/CommunicationTemplatesLetterheads/home", section: " > Email"},
  {label: "Lightning Email Templates", link: "/LightningEmailTemplateSetup/home", section: " > Email"},
  {label: "Mail Merge Templates", link: "/CommunicationTemplatesWord/home", section: " > Email"},
  {label: "Organization-Wide Addresses", link: "/OrgWideEmailAddresses/home", section: " > Email"},
  {label: "Outlook Configurations", link: "/EmailConfigurations/home", section: " > Email"},
  {label: "Outlook Integration and Sync", link: "/LightningForOutlookAndSyncSettings/home", section: " > Email"},
  {label: "Send through External Email Services", link: "/EmailTransportServiceSetupPage/home", section: " > Email"},
  {label: "Test Deliverability", link: "/TestEmailDeliverability/home", section: " > Email"},
]);

add("Platform Tools", SETUP_ROOT, [
  //Platform Tools > Apps
  {label: "App Manager", link: "/NavigationMenus/home", section: " > Apps"},
  {label: "AppExchange Marketplace", link: "/AppExchangeMarketplace/home", section: " > Apps"},
  //Platform Tools > Apps > Connected Apps
  {label: "Connected Apps OAuth Usage", link: "/ConnectedAppsUsage/home", section: " > Apps > Connected Apps"},
  {label: "Manage Connected Apps", link: "/ConnectedApplication/home", section: " > Apps > Connected Apps"},
  //Platform Tools > Apps > Lightning Bolt
  {label: "Flow Category", link: "/FlowCategory/home", section: " > Apps > Lightning Bolt"},
  {label: "Lightning Bolt Solutions", link: "/LightningBolt/home", section: " > Apps > Lightning Bolt"},
  //Platform Tools > Apps > Mobile Apps > Salesforce
  {label: "Salesforce Branding", link: "/Salesforce1Branding/home", section: " > Apps > Mobile Apps > Salesforce"},
  {label: "Salesforce Mobile Quick Start", link: "/Salesforce1SetupSection/home", section: " > Apps > Mobile Apps > Salesforce"},
  {label: "Salesforce Navigation", link: "/ProjectOneAppMenu/home", section: " > Apps > Mobile Apps > Salesforce"},
  {label: "Salesforce Notifications", link: "/NotificationsSettings/home", section: " > Apps > Mobile Apps > Salesforce"},
  {label: "Salesforce Offline", link: "/MobileOfflineStorageAdmin/home", section: " > Apps > Mobile Apps > Salesforce"},
  {label: "Salesforce Settings", link: "/Salesforce1Settings/home", section: " > Apps > Mobile Apps > Salesforce"},
  //Platform Tools > Apps > Packaging
  {label: "Installed Packages", link: "/ImportedPackage/home", section: " > Apps > Packaging"},
  {label: "Package Manager", link: "/Package/home", section: " > Apps > Packaging"},
  {label: "Package Usage", link: "/PackageUsageSummary/home", section: " > Apps > Packaging"},

  //Platform Tools > Feature Settings > Digital Experiences
  {label: "All Sites", link: "/SetupNetworks/home", section: " > Feature Settings > Digital Experiences"},
  {label: "Pages", link: "/CommunityFlexiPageList/home", section: " > Feature Settings > Digital Experiences"},
  {label: "Settings", link: "/NetworkSettings/home", section: " > Feature Settings > Digital Experiences"},
  {label: "Templates", link: "/CommunityTemplateDefinitionList/home", section: " > Feature Settings > Digital Experiences"},
  {label: "Themes", link: "/CommunityThemeDefinitionList/home", section: " > Feature Settings > Digital Experiences"},

  //Platform Tools > Feature Settings
  {label: "Functions", link: "/Functions/home", section: " > Feature Settings"},
  {label: "Home", link: "/Home/home", section: " > Feature Settings"},
  {label: "Quip (Salesforce Anywhere)", link: "/SalesforceAnywhereSetupPage/home", section: " > Feature Settings"},

  //Platform Tools > Einstein > Einstein Assessors
  {label: "Einstein Bots Assessor", link: "/EinsteinBotsReadinessCheck/home", section: " > Einstein > Einstein Assessors"},
  {label: "Einstein Conversation Insights Assessor", link: "/EinsteinCIReadinessCheck/home", section: " > Einstein > Einstein Assessors"},
  {label: "Revenue Intelligence Assessor", link: "/EinsteinRevIntlReadinessCheck/home", section: " > Einstein > Einstein Assessors"},
  {label: "Sales Cloud Einstein Assessor", link: "/SalesCloudEinsteinReadinessCheck/home", section: " > Einstein > Einstein Assessors"},
  {label: "Service Cloud Einstein Assessor", link: "lightning/setup/ServiceCloudEinsteinReadinessCheck/home", section: " > Einstein > Einstein Assessors"},
  //Platform Tools > Einstein > Einstein Platform
  {label: "Einstein Prediction Builder", link: "/EinsteinBuilder/home", section: " > Einstein > Einstein Platform"},
  {label: "Einstein Recommendation Builder", link: "/EinsteinRecommendation/home", section: " > Einstein > Einstein Platform"},
  {label: "Einstein.ai", link: "/EinsteinKeyManagement/home", section: " > Einstein > Einstein Platform"},
  //Platform Tools > Einstein > Einstein Search
  {label: "Objects to Always Search", link: "/SearchScope/home", section: " > Einstein > Einstein Search"},
  {label: "Search Layouts", link: "/EinsteinSearchLayouts/home", section: " > Einstein > Einstein Search"},
  {label: "Search Manager", link: "/SearchConfiguration/home", section: " > Einstein > Einstein Search"},
  {label: "Settings", link: "/EinsteinSearchSettings/home", section: " > Einstein > Einstein Search"},
  {label: "Synonyms", link: "/ManageSynonyms/home", section: " > Einstein > Einstein Search"},

  //Platform Tools > Feature Settings > Salesforce Files
  {label: "Asset Files", link: "/ContentAssets/home", section: " > Feature Settings > Salesforce Files"},
  {label: "Content Deliveries and Public Links", link: "/ContentDistribution/home", section: " > Feature Settings > Salesforce Files"},
  {label: "Files Connect", link: "/ContentHub/home", section: " > Feature Settings > Salesforce Files"},
  {label: "General Settings", link: "/FilesGeneralSettings/home", section: " > Feature Settings > Salesforce Files"},
  {label: "Regenerate Previews", link: "/RegeneratePreviews/home", section: " > Feature Settings > Salesforce Files"},
  {label: "Salesforce CRM Content", link: "/SalesforceCRMContent/home", section: " > Feature Settings > Salesforce Files"},

  //Platform Tools > Feature Settings > Sales
  {label: "Activity Settings", link: "/HomeActivitiesSetupPage/home", section: " > Feature Settings > Sales"},
  {label: "Contact Roles on Contracts", link: "/ContractContactRoles/home", section: " > Feature Settings > Sales"},
  {label: "Contact Roles on Opportunities", link: "/OpportunityRoles/home", section: " > Feature Settings > Sales"},
  {label: "Contract Settings", link: "/ContractSettings/home", section: " > Feature Settings > Sales"},
  {label: "Individual Settings", link: "/IndividualSettings/home", section: " > Feature Settings > Sales"},
  {label: "LinkedIn Sales Navigator", link: "/LinkedInSalesNavigatorPage/home", section: " > Feature Settings > Sales"},
  {label: "Notes Settings", link: "/NotesSetupPage/home", section: " > Feature Settings > Sales"},
  {label: "Order Settings", link: "/OrderSettings/home", section: " > Feature Settings > Sales"},
  {label: "Sales Processes", link: "/OpportunityProcess/home", section: " > Feature Settings > Sales"},
  {label: "Social Accounts and Contacts Settings", link: "/SocialProfileOrgSettings/home", section: " > Feature Settings > Sales"},
  {label: "Update Reminders", link: "/OpportunityUpdateReminders/home", section: " > Feature Settings > Sales"},

  //Platform Tools > Feature Settings > Sales > Account
  {label: "Account Settings", link: "/AccountSettings/home", section: " > Feature Settings > Sales > Account"},
  {label: "Account Teams", link: "/AccountTeamSelling/home", section: " > Feature Settings > Sales > Account"},
  {label: "Person Account", link: "/PersonAccountSettings/home", section: " > Feature Settings > Sales > Account"},

  //Platform Tools > Feature Settings > Service
  {label: "Case Assignment Rules", link: "/CaseRules/home", section: " > Feature Settings > Service"},
  {label: "Case Auto-Response Rules", link: "/CaseResponses/home", section: " > Feature Settings > Service"},
  {label: "Case Comment Triggers", link: "/CaseCommentTriggers/home", section: " > Feature Settings > Service"},
  {label: "Case Team Roles", link: "/CaseTeamRoles/home", section: " > Feature Settings > Service"},
  {label: "Predefined Case Teams", link: "/CaseTeamTemplates/home", section: " > Feature Settings > Service"},
  {label: "Contact Roles on Cases", link: "/CaseContactRoles/home", section: " > Feature Settings > Service"},
  {label: "Customer Contact Requests", link: "/ContactRequestFlows/home", section: " > Feature Settings > Service"},
  {label: "Email-to-Case", link: "/EmailToCase/home", section: " > Feature Settings > Service"},
  {label: "Escalation Rules", link: "/CaseEscRules/home", section: " > Feature Settings > Service"},
  {label: "Feed Filters", link: "/FeedFilterDefinitions/home", section: " > Feature Settings > Service"},

  //Platform Tools > Feature Settings > Service > Field Service
  {label: "Field Service Settings", link: "/FieldServiceSettings/home", section: " > Feature Settings > Service > Field Service"},
  {label: "Field Service Mobile App Builder", link: "/FieldServiceAppBuilder/home", section: " > Feature Settings > Service > Field Service"},
  {label: "Inbound Social Post Errors", link: "/InboundSocialPostErrors/homee", section: " > Feature Settings > Service > Field Service"},

  //Platform Tools > Feature Settings > Service > Knowledge
  {label: "Data Category Assignments", link: "/KnowledgeDataCategorySetup/home", section: " > Feature Settings > Service > Knowledge"},
  {label: "Data Category Mapping", link: "/ArticleFilterRules/home", section: " > Feature Settings > Service > Knowledge"},
  {label: "Knowledge Settings", link: "/KnowledgeSettings/home", section: " > Feature Settings > Service > Knowledge"},
  {label: "Validation Statuses", link: "/ValidationStatuses/home", section: " > Feature Settings > Service > Knowledge"},

  {label: "Macro Settings", link: "/MacroSettings/home", section: " > Feature Settings > Service"},
  {label: "Omni-Channel Settings", link: "/OmniChannelSettings/home", section: " > Feature Settings > Service"},
  {label: "Snap-ins", link: "/Snap-ins/home", section: " > Feature Settings > Service"},
  {label: "Social Business Rules", link: "/SocialCustomerServiceBusinessRules/home", section: " > Feature Settings > Service"},
  {label: "Social Customer Service", link: "/SocialCustomerManagementAccountSettings/home", section: " > Feature Settings > Service"},
  {label: "Support Processes", link: "/CaseProcess/home", section: " > Feature Settings > Service"},
  {label: "Support Settings", link: "/CaseSettings/home", section: " > Feature Settings > Service"},
  {label: "Web-to-Case", link: "/CaseWebtocase/home", section: " > Feature Settings > Service"},
  {label: "Web-to-Case HTML Generator", link: "/CaseWebToCaseHtmlGenerator/home", section: " > Feature Settings > Service"},
  //Platform Tools > Feature Settings > Survey
  {label: "Survey Settings", link: "/SurveySettings/home", section: " > Feature Settings > Survey"},
  //Platform Tools > Objects and Fields
  {label: "Object Manager", link: "/ObjectManager/home", section: " > Objects and Fields"},
  {label: "Picklist Value Sets", link: "/Picklists/home", section: " > Objects and Fields"},
  {label: "Schema Builder", link: "/SchemaBuilder/home", section: " > Objects and Fields"},
  //Platform Tools > Events
  {label: "Event Manager", link: "/EventManager/home", section: " > Events"},
  //Platform Tools > Process Automation
  {label: "Approval Processes", link: "/ApprovalProcesses/home", section: " > Process Automation"},
  {label: "Automation Home", link: "/ProcessHome/home", section: " > Process Automation"},
  {label: "Flows", link: "/Flows/home", section: " > Process Automation"},
  {label: "Migrate to Flow", link: "/MigrateToFlowTool/home", section: " > Process Automation"},
  {label: "Next Best Action", link: "/NextBestAction/home", section: " > Process Automation"},
  {label: "Paused And Failed Flow Interviews", link: "/Pausedflows/home", section: " > Process Automation"},
  {label: "Post Templates", link: "/FeedTemplates/home", section: " > Process Automation"},
  {label: "Process Automation Settings", link: "/WorkflowSettings/home", section: " > Process Automation"},
  {label: "Process Builder", link: "/ProcessAutomation/home", section: " > Process Automation"},

  {label: "Email Alerts", link: "/WorkflowEmails/home", section: " > Process Automation > Workflow Actions"},
  {label: "Field Updates", link: "/WorkflowFieldUpdates/home", section: " > Process Automation > Workflow Actions"},
  {label: "Outbound Messages", link: "/WorkflowOutboundMessaging/home", section: " > Process Automation > Workflow Actions"},
  {label: "Send Actions", link: "/SendAction/home", section: " > Process Automation > Workflow Actions"},
  {label: "Tasks", link: "/WorkflowTasks/home", section: " > Process Automation > Workflow Actions"},
  {label: "Workflow Rules", link: "/WorkflowRules/home", section: " > Process Automation"},
  //User Interface
  {label: "Action Link Templates", link: "/ActionLinkGroupTemplates/home", section: " > User Interface"},
  {label: "Guided Actions", link: "/GuidedActions/home", section: " > User Interface"},
  {label: "App Menu", link: "/AppMenu/home", section: " > User Interface"},
  {label: "Custom Labels", link: "/ExternalStrings/home", section: " > User Interface"},
  {label: "Density Settings", link: "/DensitySetup/home", section: " > User Interface"},

  {label: "Global Actions", link: "/GlobalActions/home", section: " > User Interface > Global Actions"},
  {label: "Publisher Layouts", link: "/GlobalPublisherLayouts/home", section: " > User Interface > Global Actions"},

  {label: "Lightning App Builder", link: "/FlexiPageList/home", section: " > User Interface"},
  {label: "Lightning Extension", link: "/LightningExtension/home", section: " > User Interface"},
  {label: "Loaded Console Tab Limit", link: "/ConsoleMaxTabCacheSetup/home", section: " > User Interface"},
  {label: "Path Settings", link: "/PathAssistantSetupHome/home", section: " > User Interface"},
  {label: "Quick Text Settings", link: "/LightningQuickTextSettings/home", section: " > User Interface"},
  {label: "Record Page Settings", link: "/SimpleRecordHome/home", section: " > User Interface"},
  {label: "Rename Tabs and Labels", link: "/RenameTab/home", section: " > User Interface"},
  //Sites and Domains
  {label: "Custom URLs", link: "/DomainSites/home", section: " > User Interface > Sites and Domains"},
  {label: "Domains", link: "/DomainNames/home", section: " > User Interface > Sites and Domains"},
  {label: "Sites", link: "/CustomDomain/home", section: " > User Interface > Sites and Domains"},

  {label: "Tabs", link: "/CustomTabs/home", section: " > User Interface"},
  {label: "Themes and Branding", link: "/ThemingAndBranding/home", section: " > User Interface"},
  //Translation Workbench
  {label: "Data Translation Settings", link: "/LabelWorkbenchDataTranslationSetup/home", section: " > User Interface > Translation Workbench"},
  {label: "Export", link: "/LabelWorkbenchExport/home", section: " > User Interface > Translation Workbench"},
  {label: "Import", link: "/LabelWorkbenchImport/home", section: " > User Interface > Translation Workbench"},
  {label: "Override", link: "/LabelWorkbenchOverride/home", section: " > User Interface > Translation Workbench"},
  {label: "Translate", link: "/LabelWorkbenchTranslate/home", section: " > User Interface > Translation Workbench"},
  {label: "Translation Settings", link: "/LabelWorkbenchSetup/home", section: " > User Interface > Translation Workbench"},

  {label: "User Interface", link: "/UserInterfaceUI/home", section: " > User Interface"},
  //Custom Code
  {label: "Apex Classes", link: "/ApexClasses/home", section: " > Custom Code"},
  {label: "Apex Hammer Test Results", link: "/ApexHammerResultStatus/home", section: " > Custom Code"},
  {label: "Apex Settings", link: "/ApexSettings/home", section: " > Custom Code"},
  {label: "Apex Test Execution", link: "/ApexTestQueue/home", section: " > Custom Code"},
  {label: "Apex Test History", link: "/ApexTestHistory/home", section: " > Custom Code"},
  {label: "Apex Triggers", link: "/ApexTriggers/home", section: " > Custom Code"},
  {label: "Canvas App Previewer", link: "/CanvasPreviewerUi/home", section: " > Custom Code"},
  {label: "Custom Metadata Types", link: "/CustomMetadata/home", section: " > Custom Code"},
  {label: "Custom Permissions", link: "/CustomPermissions/home", section: " > Custom Code"},
  {label: "Custom Settings", link: "/CustomSettings/home", section: " > Custom Code"},
  {label: "Email Services", link: "/EmailToApexFunction/home", section: " > Custom Code"},
  //Lightning Components
  {label: "Debug Mode", link: "/UserDebugModeSetup/home", section: " > Custom Code > Lightning Components"},
  {label: "Lightning Components", link: "/LightningComponentBundles/home", section: " > Custom Code > Lightning Components"},

  {label: "Platform Cache", link: "/PlatformCache/home", section: " > Custom Code"},
  {label: "Remote Access", link: "/RemoteAccess/home", section: " > Custom Code"},
  {label: "Static Resources", link: "/StaticResources/home", section: " > Custom Code"},
  {label: "Tools", link: "/ClientDevTools/home", section: " > Custom Code"},
  {label: "Visualforce Components", link: "/ApexComponents/home", section: " > Custom Code"},
  {label: "Visualforce Pages", link: "/ApexPages/home", section: " > Custom Code"},
  //Development
  {label: "Dev Hub", link: "/DevHub/home", section: " > Dev Hub", prod: true},
  {label: "DevOps Center", link: "/DevOpsCenterSetup/home", section: " > Dev Hub", prod: true},
  {label: "Org Shape", link: "/ShapeGrantAccess/home", section: " > Dev Hub", prod: true},
  //Performance
  {label: "Performance Assistant", link: "/PerformanceAssistant/home", section: " > Performance > Performance Testing"},
  //Platform Tools > Environments
  {label: "Inbound Change Sets", link: "/InboundChangeSet/home", section: " > Environments > Change Sets"},
  {label: "Outbound Change Sets", link: "/OutboundChangeSet/home", section: " > Environments > Change Sets"},
  //Platform Tools > Environments > Deploy
  {label: "Deployment Settings", link: "/DeploymentSettings/home", section: " > Environments > Deploy"},
  {label: "Deployment Status", link: "/DeployStatus/home", section: " > Environments > Deploy"},
  //Platform Tools > Environments > Jobs
  {label: "Apex Flex Queue", link: "/ApexFlexQueue/home", section: " > Environments > Jobs"},
  {label: "Apex Jobs", link: "/AsyncApexJobs/home", section: " > Environments > Jobs"},
  {label: "Background Jobs", link: "/ParallelJobsStatus/home", section: " > Environments > Jobs"},
  {label: "Bulk Data Load Jobs", link: "/AsyncApiJobStatus/home", section: " > Environments > Jobs"},
  {label: "Scheduled Jobs", link: "/ScheduledJobs/home", section: " > Environments > Jobs"},
  //Platform Tools > Environments > Logs
  {label: "Debug Logs", link: "/ApexDebugLogs/home", section: " > Environments > Logs"},
  {label: "Email Log Files", link: "/EmailLogFiles/home", section: " > Environments > Logs"},
  //Platform Tools > Environments > Monitoring
  {label: "API Usage Notifications", link: "/MonitoringRateLimitingNotification/home", section: " > Environments > Monitoring"},
  {label: "Case Escalations", link: "/DataManagementManageCaseEscalation/home", section: " > Environments > Monitoring"},
  {label: "Email Snapshots", link: "/EmailCapture/home", section: " > Environments > Monitoring"},
  {label: "Outbound Messages", link: "/WorkflowOmStatus/home", section: " > Environments > Monitoring"},
  {label: "Time-Based Workflow", link: "/DataManagementManageWorkflowQueue/home", section: " > Environments > Monitoring"},

  {label: "Sandboxes", link: "/DataManagementCreateTestInstance/home", section: " > Environments", prod: true},
  {label: "System Overview", link: "/SystemOverview/home", section: " > Environments"},
  //Platform Tools > User Engagement
  {label: "Adoption Assistance", link: "/AdoptionAssistance/home", section: " > User Engagement"},
  {label: "Guidance Center", link: "/LearningSetup/home", section: " > User Engagement"},
  {label: "Help Menu", link: "/HelpMenu/home", section: " > User Engagement"},
  {label: "In-App Guidance", link: "/Prompts/home", section: " > User Engagement"},
  //Platform Tools > Integrations
  {label: "API", link: "/WebServices/home", section: " > Integrations"},
  {label: "Basic Data Import", link: "/BasicDataImport/home", section: " > Integrations"},
  {label: "Change Data Capture", link: "/CdcObjectEnablement/home", section: " > Integrations"},
  {label: "Data Import Wizard", link: "/DataManagementDataImporter/home", section: " > Integrations"},
  {label: "Data Loader", link: "/DataLoader/home", section: " > Integrations"},
  {label: "Dataloader.io", link: "/DataLoaderIo/home", section: " > Integrations"},
  {label: "External Data Sources", link: "/ExternalDataSource/home", section: " > Integrations"},
  {label: "External Objects", link: "/ExternalObjects/home", section: " > Integrations"},
  {label: "External Services", link: "/ExternalServices/home", section: " > Integrations"},
  {label: "Platform Events", link: "/EventObjects/home", section: " > Integrations"},
  {label: "Teams Integration", link: "/MicrosoftTeamsIntegration/home", section: " > Integrations"},
  //Platform Tools > Notification Builder
  {label: "Custom Notifications", link: "/CustomNotifications/home", section: " > Notification Builder"},
  {label: "Notification Delivery Settings", link: "/NotificationTypesManager/home", section: " > Notification Builder"}
]);

add("Settings", SETUP_ROOT, [
  //Settings > Company Settings
  {label: "Business Hours", link: "/BusinessHours/home", section: " > Company Settings"},
  {label: "Public Calendars and Resources", link: "/Calendars/home", section: " > Company Settings > Calendar Settings"},
  {label: "Company Information", link: "/CompanyProfileInfo/home", section: " > Company Settings"},
  {label: "Data Protection and Privacy", link: "/ConsentManagement/home", section: " > Company Settings"},
  {label: "Fiscal Year", link: "/ForecastFiscalYear/home", section: " > Company Settings"},
  {label: "Holidays", link: "/Holiday/home", section: " > Company Settings"},
  {label: "Language Settings", link: "/LanguageSettings/home", section: " > Company Settings"},
  {label: "Manage Currencies", link: "/CompanyCurrency/home", section: " > Company Settings"},
  {label: "Maps and Location Settings", link: "/MapsAndLocationServicesSettings/home", section: " > Company Settings"},
  {label: "My Domain", link: "/OrgDomain/home", section: " > Company Settings"},
  //Settings > Data Classification
  {label: "Data Classification", link: "/DataClassificationSettings/home", section: " > Data Classification"},
  {label: "Data Classification Download", link: "/DataClassificationDownload/home", section: " > Data Classification"},
  {label: "Data Classification Upload", link: "/DataClassificationUpload/home", section: " > Data Classification"},
  //Settings > Privacy Center
  {label: "Consent Event Stream", link: "/ConsentEventStream/home", section: " > Privacy Center"},
  //Settings > Identity
  {label: "Auth. Providers", link: "/AuthProviders/home", section: " > Identity"},
  {label: "Identity Provider", link: "/IdpPage/home", section: " > Identity"},
  {label: "Identity Provider Event Log", link: "/IdpErrorLog/home", section: " > Identity"},
  {label: "Identity Verification", link: "/IdentityVerification/home", section: " > Identity"},
  {label: "Identity Verification History", link: "/VerificationHistory/home", section: " > Identity"},
  {label: "Login Flows", link: "/LoginFlow/home", section: " > Identity"},
  {label: "Login History", link: "/OrgLoginHistory/home", section: " > Identity"},
  {label: "OAuth Custom Scopes", link: "/OauthCustomScope/home", section: " > Identity"},
  {label: "OAuth and OpenID Connect Settings", link: "/OauthOidcSettings/home", section: " > Identity"},
  {label: "Single Sign-On Settings", link: "/SingleSignOn/home", section: " > Identity"},
  //Settings > Security
  {label: "Account Owner Report", link: "/SecurityAccountOwner/home", section: " > Security"},
  {label: "Activations", link: "/ActivatedIpAddressAndClientBrowsersPage/home", section: " > Security"},
  {label: "CORS", link: "/CorsWhitelistEntries/home", section: " > Security"},
  {label: "CSP Trusted Sites", link: "/SecurityCspTrustedSite/home", section: " > Security"},
  {label: "Certificate and Key Management", link: "/CertificatesAndKeysManagement/home", section: " > Security"},
  {label: "Delegated Administration", link: "/DelegateGroups/home", section: " > Security"},
  //Settings > Security > Event Monitoring
  {label: "Event Monitoring Settings", link: "/EventMonitoringSetup/home", section: " > Security > Event Monitoring"},
  {label: "Transaction Security Policies", link: "/TransactionSecurityNew/home", section: " > Security > Event Monitoring"},
  //Settings > Security
  {label: "Expire All Passwords", link: "/SecurityExpirePasswords/home", section: " > Security"},
  {label: "Field Accessibility", link: "/FieldAccessibility/home", section: " > Security"},
  {label: "File Upload and Download Security", link: "/FileTypeSetting/home", section: " > Security"},
  {label: "Health Check", link: "/HealthCheck/home", section: " > Security"},
  {label: "Login Access Policies", link: "/LoginAccessPolicies/home", section: " > Security"},
  {label: "Named Credentials", link: "/NamedCredential/home", section: " > Security"},
  {label: "Network Access", link: "/NetworkAccess/home", section: " > Security"},
  {label: "Password Policies", link: "/SecurityPolicies/home", section: " > Security"},
  //Settings > Security > Platform Encryption
  {label: "Advanced Settings", link: "/SecurityRemoteProxy/home", section: " > Security > Platform Encryption"},
  {label: "Encryption Policy", link: "/EncryptionPolicy/home", section: " > Security > Platform Encryption"},
  {label: "Encryption Statistics", link: "/EncryptionStatistics/home", section: " > Security > Platform Encryption"},
  {label: "Key Management", link: "/PlatformEncryptionKeyManagement/home", section: " > Security > Platform Encryption"},
  //Settings > Security
  {label: "Portal Health Check", link: "/PortalSecurityReport/home", section: " > Security"},
  {label: "Private Connect", link: "/PrivateConnect/home", section: " > Security"},
  {label: "Remote Site Settings", link: "/SecurityRemoteProxy/home", section: " > Security"},
  {label: "Session Management", link: "/SessionManagementPage/home", section: " > Security"},
  {label: "Session Settings", alias: "LWC Caching", link: "/SecuritySession/home", section: " > Security"},
  {label: "Sharing Settings", alias: "Org Wide Defaults, OWD", link: "/SecuritySharing/home", section: " > Security"},
  {label: "Trusted URLs for Redirects", link: "/SecurityRedirectWhitelistUrl/home", section: " > Security"},
  {label: "View Setup Audit Trail", link: "/SecurityEvents/home", section: " > Security"},
]);

//Custom Link: exception to link pattern, just push as-is
setupLinks.push(
  {label: "Create New Flow", link: "/builder_platform_interaction/flowBuilder.app", section: "Platform Tools > Objects and Fields > New"}
);
add("", "/lightning", [
  {label: "Create New Custom Object", link: "/setup/ObjectManager/new", section: "Platform Tools > Process Automation"},
  {label: "Create New Permission Set", link: "/setup/PermSets/page?address=/udd/PermissionSet/newPermissionSet.apexp", section: "Administration > Users > Permission Set"},
  {label: "Create New Custom Permission", link: "/setup/CustomPermissions/page?address=/0CP/e", section: "Platform Tools > Custom Code > Custom Permission"},
  {label: "Recycle Bin", link: "/o/DeleteEvent/home", section: "App Launcher > Custom Link"},
]);

setupLinks.push(...[
  //ConnectApi namespace classes doc links
  {label: "Class ActionLinks", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ActionLinks_static_methods.htm", section: "Documentation Apex> ConnectApi > ActionLinks", isExternal: true},
  {label: "Class Announcements", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Announcements_static_methods.htm", section: "Documentation Apex> ConnectApi > Announcements", isExternal: true},
  {label: "Class BotVersionActivation", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_BotVersionActivation_static_methods.htm", section: "Documentation Apex> ConnectApi > BotVersionActivation", isExternal: true},
  {label: "Class CdpCalculatedInsight", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpCalculatedInsight_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpCalculatedInsight", isExternal: true},
  {label: "Class CdpIdentityResolution", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpIdentityResolution_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpIdentityResolution", isExternal: true},
  {label: "Class CdpQuery", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpQuery_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpQuery", isExternal: true},
  {label: "Class CdpSegment", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpSegment_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpSegment", isExternal: true},
  {label: "Class Chatter", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Chatter_static_methods.htm", section: "Documentation Apex> ConnectApi > Chatter", isExternal: true},
  {label: "Class ChatterFavorites", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterFavorites_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterFavorites", isExternal: true},
  {label: "Class ChatterFeeds", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterFeeds_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterFeeds", isExternal: true},
  {label: "Class ChatterGroups", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterGroups_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterGroups", isExternal: true},
  {label: "Class ChatterMessages", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterMessages_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterMessages", isExternal: true},
  {label: "Class ChatterUsers", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterUsers_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterUsers", isExternal: true},
  {label: "Class Clm", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Clm_static_methods.htm", section: "Documentation Apex> ConnectApi > Clm", isExternal: true},
  {label: "Class CommerceBuyerExperience", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceBuyerExperience_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceBuyerExperience", isExternal: true},
  {label: "Class CommerceCart", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceCart_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceCart", isExternal: true},
  {label: "Class CommerceCatalog", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceCatalog_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceCatalog", isExternal: true},
  {label: "Class CommercePromotions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommercePromotions_static_methods.htm", section: "Documentation Apex> ConnectApi > CommercePromotions", isExternal: true},
  {label: "Class CommerceSearch", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceSearch_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceSearch", isExternal: true},
  {label: "Class CommerceSearchConnectFamily", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceSearchConnectFamily_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceSearchConnectFamily", isExternal: true},
  {label: "Class CommerceSearchSettings", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceSearchSettings_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceSearchSettings", isExternal: true},
  {label: "Class CommerceStorePricing", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceStorePricing_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceStorePricing", isExternal: true},
  {label: "Class CommerceWishlist", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceWishlist_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceWishlist", isExternal: true},
  {label: "Class Communities", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Communities_static_methods.htm", section: "Documentation Apex> ConnectApi > Communities", isExternal: true},
  {label: "Class CommunityModeration", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommunityModeration_static_methods.htm", section: "Documentation Apex> ConnectApi > CommunityModeration", isExternal: true},
  {label: "Class ContentHub", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ContentHub_static_methods.htm", section: "Documentation Apex> ConnectApi > ContentHub", isExternal: true},
  {label: "Class ConversationApplicationDefinition", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ConversationApplicationDefinition_static_methods.htm", section: "Documentation Apex> ConnectApi > ConversationApplicationDefinition", isExternal: true},
  {label: "Class Datacloud", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Datacloud_static_methods.htm", section: "Documentation Apex> ConnectApi > Datacloud", isExternal: true},
  {label: "Class EmailMergeFieldService", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_EmailMergeFieldService_static_methods.htm", section: "Documentation Apex> ConnectApi > EmailMergeFieldService", isExternal: true},
  {label: "Class EmployeeProfiles", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_EmployeeProfiles_static_methods.htm", section: "Documentation Apex> ConnectApi > EmployeeProfiles", isExternal: true},
  {label: "Class ExternalEmailServices", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ExternalEmailService_static_methods.htm", section: "Documentation Apex> ConnectApi > ExternalEmailServices", isExternal: true},
  {label: "Class ExternalManagedAccount", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ExternalManagedAccount_static_methods.htm", section: "Documentation Apex> ConnectApi > ExternalManagedAccount", isExternal: true},
  {label: "Class FieldService", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_FieldService_static_methods.htm", section: "Documentation Apex> ConnectApi > FieldService", isExternal: true},
  {label: "Class FulfillmentOrder", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_FulfillmentOrder_static_methods.htm", section: "Documentation Apex> ConnectApi > FulfillmentOrder", isExternal: true},
  {label: "Class Knowledge", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Knowledge_static_methods.htm", section: "Documentation Apex> ConnectApi > Knowledge", isExternal: true},
  {label: "Class LightningScheduler", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_LightningScheduler_static_methods.htm", section: "Documentation Apex> ConnectApi > LightningScheduler", isExternal: true},
  {label: "Class ManagedContent", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ManagedContent_static_methods.htm", section: "Documentation Apex> ConnectApi > ManagedContent", isExternal: true},
  {label: "Class ManagedContentDelivery", link: "", section: "Documentation Apex> ConnectApi > ManagedContentDelivery", isExternal: true},
  {label: "Class ManagedTopics", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ManagedTopics_static_methods.htm", section: "Documentation Apex> ConnectApi > ManagedTopics", isExternal: true},
  {label: "Class MarketingIntegration", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_MarketingIntegration_static_methods.htm", section: "Documentation Apex> ConnectApi > MarketingIntegration", isExternal: true},
  {label: "Class Mentions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Mentions_static_methods.htm", section: "Documentation Apex> ConnectApi > Mentions", isExternal: true},
  {label: "Class Missions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Missions_static_methods.htm", section: "Documentation Apex> ConnectApi > Missions", isExternal: true},
  {label: "Class NamedCredentials", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_NamedCredentials_static_methods.htm", section: "Documentation Apex> ConnectApi > NamedCredentials", isExternal: true},
  {label: "Class NavigationMenu", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_NavigationMenu_static_methods.htm", section: "Documentation Apex> ConnectApi > NavigationMenu", isExternal: true},
  {label: "Class NextBestAction", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_NextBestAction_static_methods.htm", section: "Documentation Apex> ConnectApi > NextBestAction", isExternal: true},
  {label: "Class OmnichannelInventoryService", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OmnichannelInventoryService_static_methods.htm", section: "Documentation Apex> ConnectApi > OmnichannelInventoryService", isExternal: true},
  {label: "Class Orchestration", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Orchestration_static_methods.htm", section: "Documentation Apex> ConnectApi > Orchestration", isExternal: true},
  {label: "Class OrderPaymentSummary", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OrderPaymentSummary_static_methods.htm", section: "Documentation Apex> ConnectApi > OrderPaymentSummary", isExternal: true},
  {label: "Class OrderSummary", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OrderSummary_static_methods.htm", section: "Documentation Apex> ConnectApi > OrderSummary", isExternal: true},
  {label: "Class OrderSummaryCreation", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OrderSummaryCreation_static_methods.htm", section: "Documentation Apex> ConnectApi > OrderSummaryCreation", isExternal: true},
  {label: "Class Organization", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Organization_static_methods.htm", section: "Documentation Apex> ConnectApi > Organization", isExternal: true},
  {label: "Class PardotBusinessUnitContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_PardotBusinessUnitContext_static_methods.htm", section: "Documentation Apex> ConnectApi > PardotBusinessUnitContext", isExternal: true},
  {label: "Class Payments", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Payments_static_methods.htm", section: "Documentation Apex> ConnectApi > Payments", isExternal: true},
  {label: "Class Personalization", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Personalization_static_methods.htm", section: "Documentation Apex> ConnectApi > Personalization", isExternal: true},
  {label: "Class PickTicket", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_PickTicket_static_methods.htm", section: "Documentation Apex> ConnectApi > PickTicket", isExternal: true},
  {label: "Class QuestionAndAnswers", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_QuestionAndAnswers_static_methods.htm", section: "Documentation Apex> ConnectApi > QuestionAndAnswers", isExternal: true},
  {label: "Class Recommendations", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Recommendations_static_methods.htm", section: "Documentation Apex> ConnectApi > Recommendations", isExternal: true},
  {label: "Class Records", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Records_static_methods.htm", section: "Documentation Apex> ConnectApi > Records", isExternal: true},
  {label: "Class Repricing", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Repricing_static_methods.htm", section: "Documentation Apex> ConnectApi > Repricing", isExternal: true},
  {label: "Class ReturnOrder", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ReturnOrder_static_methods.htm", section: "Documentation Apex> ConnectApi > ReturnOrder", isExternal: true},
  {label: "Class Routing", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Routing_static_methods.htm", section: "Documentation Apex> ConnectApi > Routing", isExternal: true},
  {label: "Class SalesforceInbox", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_SalesforceInbox_static_methods.htm", section: "Documentation Apex> ConnectApi > SalesforceInbox", isExternal: true},
  {label: "Class Sites", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Sites_static_methods.htm", section: "Documentation Apex> ConnectApi > Sites", isExternal: true},
  {label: "Class SocialEngagement", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_SocialEngagement_static_methods.htm", section: "Documentation Apex> ConnectApi > SocialEngagement", isExternal: true},
  {label: "Class Surveys", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Survey_static_methods.htm", section: "Documentation Apex> ConnectApi > Surveys", isExternal: true},
  {label: "Class TaxPlatform", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_TaxPlatform_static_methods.htm", section: "Documentation Apex> ConnectApi > TaxPlatform", isExternal: true},
  {label: "Class Topics", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Topics_static_methods.htm", section: "Documentation Apex> ConnectApi > Topics", isExternal: true},
  {label: "Class UserProfiles", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_UserProfiles_static_methods.htm", section: "Documentation Apex> ConnectApi > UserProfiles", isExternal: true},
  {label: "Class Zones", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Zones_static_methods.htm", section: "Documentation Apex> ConnectApi > Zones", isExternal: true},
  {label: "Class ConnectApi Input", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_connectapi_input.htm", section: "Documentation Apex> ConnectApi > ActionLinks", isExternal: true},
  {label: "Class ConnectApi Output", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_connectapi_output.htm", section: "Documentation Apex> ConnectApi > ConnectApi Output", isExternal: true},
  //Database namespace classes doc links
  {label: "Class Batchable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_database_batchable.htm", section: "Documentation Apex> Database > Batchable", isExternal: true},
  {label: "Class BatchableContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_database_batchablecontext.htm", section: "Documentation Apex> Database > BatchableContext", isExternal: true},
  {label: "Class DeletedRecord", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_deletedrecord.htm", section: "Documentation Apex> Database > DeletedRecord", isExternal: true},
  {label: "Class DeleteResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_deleteresult.htm", section: "Documentation Apex> Database > DeleteResult", isExternal: true},
  {label: "Class DMLOptions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_dmloptions.htm", section: "Documentation Apex> Database > DMLOptions", isExternal: true},
  {label: "Class DuplicateError", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_Database_DuplicateError.htm", section: "Documentation Apex> Database > DuplicateError", isExternal: true},
  {label: "Class EmptyRecycleBinResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_EmptyRecycleBinResult.htm", section: "Documentation Apex> Database > EmptyRecycleBinResult", isExternal: true},
  {label: "Class Error", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_error.htm", section: "Documentation Apex> Database > Error", isExternal: true},
  {label: "Class GetDeletedResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_getdeletedresult.htm", section: "Documentation Apex> Database > GetDeletedResult", isExternal: true},
  {label: "Class GetUpdatedResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_getupdatedresult.htm", section: "Documentation Apex> Database > GetUpdatedResult", isExternal: true},
  {label: "Class LeadConvert", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_dml_convertLead.htm", section: "Documentation Apex> Database > LeadConvert", isExternal: true},
  {label: "Class LeadConvertResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_leadconvertresult.htm", section: "Documentation Apex> Database > LeadConvertResult", isExternal: true},
  {label: "Class MergeResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_mergeresult.htm", section: "Documentation Apex> Database > MergeResult", isExternal: true},
  {label: "Class QueryLocator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_batch.htm", section: "Documentation Apex> Database > QueryLocator", isExternal: true},
  {label: "Class QueryLocatorIterator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_querylocatoriterator.htm", section: "Documentation Apex> Database > QueryLocatorIterator", isExternal: true},
  {label: "Class SaveResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_saveresult.htm", section: "Documentation Apex> Database > SaveResult", isExternal: true},
  {label: "Class UndeleteResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_undeleteresult.htm", section: "Documentation Apex> Database > UndeleteResult", isExternal: true},
  {label: "Class UpsertResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_upsertresult.htm", section: "Documentation Apex> Database > UpsertResult", isExternal: true},
  //System namespace classes doc links
  {label: "Class AccessLevel", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_AccessLevel.htm", section: "Documentation Apex> System > AccessLevel", isExternal: true},
  {label: "Class Address", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_Address.htm", section: "Documentation Apex> System > Address", isExternal: true},
  {label: "Class Answers", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_answers.htm", section: "Documentation Apex> System > Answers", isExternal: true},
  {label: "Class ApexPages", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_apexpages.htm", section: "Documentation Apex> System > ApexPages", isExternal: true},
  {label: "Class Approval", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_approval.htm", section: "Documentation Apex> System > Approval", isExternal: true},
  {label: "Class Assert", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Assert.htm", section: "Documentation Apex> System > Assert", isExternal: true},
  {label: "Class AsyncInfo", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_AsyncInfo.htm", section: "Documentation Apex> System > AsyncInfo", isExternal: true},
  {label: "Class AsyncOptions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_AsyncOptions.htm", section: "Documentation Apex> System > AsyncOptions", isExternal: true},
  {label: "Class Blob", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_blob.htm", section: "Documentation Apex> System > Blob", isExternal: true},
  {label: "Class Boolean", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_boolean.htm", section: "Documentation Apex> System > Boolean", isExternal: true},
  {label: "Class BusinessHours", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_businesshours.htm", section: "Documentation Apex> System > BusinessHours", isExternal: true},
  {label: "Class Callable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_Callable.htm", section: "Documentation Apex> System > Callable", isExternal: true},
  {label: "Class Cases", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_System_Cases_methods.htm", section: "Documentation Apex> System > Cases", isExternal: true},
  {label: "Class Collator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Collator.htm", section: "Documentation Apex> System > Collator", isExternal: true},
  {label: "Class Comparable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_comparable.htm", section: "Documentation Apex> System > Comparable", isExternal: true},
  {label: "Class Comparator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_Comparator.htm", section: "Documentation Apex> System > Comparator", isExternal: true},
  {label: "Class Continuation", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Continuation.htm", section: "Documentation Apex> System > Continuation", isExternal: true},
  {label: "Class Cookie", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_sites_cookie.htm", section: "Documentation Apex> System > Cookie", isExternal: true},
  {label: "Class Crypto", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_crypto.htm", section: "Documentation Apex> System > Crypto", isExternal: true},
  {label: "Class Custom Metadata Type", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_metadata_types.htm", section: "Documentation Apex> System > Custom Metadata Type", isExternal: true},
  {label: "Class Custom Settings", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_settings.htm", section: "Documentation Apex> System > Custom Settings", isExternal: true},
  {label: "Class Database", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database.htm", section: "Documentation Apex> System > Database", isExternal: true},
  {label: "Class Date", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_date.htm", section: "Documentation Apex> System > Date", isExternal: true},
  {label: "Class Datetime", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_datetime.htm", section: "Documentation Apex> System > Datetime", isExternal: true},
  {label: "Class Decimal", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_decimal.htm", section: "Documentation Apex> System > Decimal", isExternal: true},
  {label: "Class Domain", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Domain.htm", section: "Documentation Apex> System > Domain", isExternal: true},
  {label: "Class DomainCreator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_DomainCreator.htm", section: "Documentation Apex> System > DomainCreator", isExternal: true},
  {label: "Class DomainParser", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_DomainParser.htm", section: "Documentation Apex> System > DomainParser", isExternal: true},
  {label: "Class Double", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_double.htm", section: "Documentation Apex> System > Double", isExternal: true},
  {label: "Class EmailMessages", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_emailmessages.htm", section: "Documentation Apex> System > EmailMessages", isExternal: true},
  {label: "Class EncodingUtil", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_encodingUtil.htm", section: "Documentation Apex> System > EncodingUtil", isExternal: true},
  {label: "Class EventBus", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_eventbus.htm", section: "Documentation Apex> System > EventBus", isExternal: true},
  {label: "Class FlexQueue", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FlexQueue.htm", section: "Documentation Apex> System > FlexQueue", isExternal: true},
  {label: "Class FeatureManagement", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FeatureManagement.htm", section: "Documentation Apex> System > FeatureManagement", isExternal: true},
  {label: "Class Formula", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Formula.htm", section: "Documentation Apex> System > Formula", isExternal: true},
  {label: "Class FormulaRecalcFieldError", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FormulaRecalcFieldError.htm", section: "Documentation Apex> System > FormulaRecalcFieldError", isExternal: true},
  {label: "Class FormulaRecalcResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FormulaRecalcResult.htm", section: "Documentation Apex> System > FormulaRecalcResult", isExternal: true},
  {label: "Class Http", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_http_http.htm", section: "Documentation Apex> System > Http", isExternal: true},
  {label: "Class HttpCalloutMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_httpcalloutmock.htm", section: "Documentation Apex> System > HttpCalloutMock", isExternal: true},
  {label: "Class HttpRequest", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_http_httprequest.htm", section: "Documentation Apex> System > HttpRequest", isExternal: true},
  {label: "Class HttpResponse", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_http_httpresponse.htm", section: "Documentation Apex> System > HttpResponse", isExternal: true},
  {label: "Class Id", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_id.htm", section: "Documentation Apex> System > Id", isExternal: true},
  {label: "Class Ideas", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_ideas.htm", section: "Documentation Apex> System > Ideas", isExternal: true},
  {label: "Class InstallHandler", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_install_handler.htm", section: "Documentation Apex> System > InstallHandler", isExternal: true},
  {label: "Class Integer", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_integer.htm", section: "Documentation Apex> System > Integer", isExternal: true},
  {label: "Class JSON", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Json.htm", section: "Documentation Apex> System > JSON", isExternal: true},
  {label: "Class JSONGenerator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_JsonGenerator.htm", section: "Documentation Apex> System > JSONGenerator", isExternal: true},
  {label: "Class JSONParser", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_JsonParser.htm", section: "Documentation Apex> System > JSONParser", isExternal: true},
  {label: "Class Label", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Label.htm", section: "Documentation Apex> System > Label", isExternal: true},
  {label: "Class Limits", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm", section: "Documentation Apex> System > Limits", isExternal: true},
  {label: "Class List", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_list.htm", section: "Documentation Apex> System > List", isExternal: true},
  {label: "Class Location", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_Location.htm", section: "Documentation Apex> System > Location", isExternal: true},
  {label: "Class Long", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_long.htm", section: "Documentation Apex> System > Long", isExternal: true},
  {label: "Class Map", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_map.htm", section: "Documentation Apex> System > Map", isExternal: true},
  {label: "Class Matcher", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_pattern_and_matcher_matcher_methods.htm", section: "Documentation Apex> System > Matcher", isExternal: true},
  {label: "Class Math", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_math.htm", section: "Documentation Apex> System > Math", isExternal: true},
  {label: "Class Messaging", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_email_outbound_messaging.htm", section: "Documentation Apex> System > Messaging", isExternal: true},
  {label: "Class MultiStaticResourceCalloutMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_multistaticresourcecalloutmock.htm", section: "Documentation Apex> System > MultiStaticResourceCalloutMock", isExternal: true},
  {label: "Class Network", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_network.htm", section: "Documentation Apex> System > Network", isExternal: true},
  {label: "Class OrgLimit", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_OrgLimit.htm", section: "Documentation Apex> System > OrgLimit", isExternal: true},
  {label: "Class OrgLimits", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_OrgLimits.htm", section: "Documentation Apex> System > OrgLimits", isExternal: true},
  {label: "Class PageReference", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_system_pagereference.htm", section: "Documentation Apex> System > PageReference", isExternal: true},
  {label: "Class Packaging", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_Packaging.htm", section: "Documentation Apex> System > Packaging", isExternal: true},
  {label: "Class Pattern", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_pattern_and_matcher_pattern_methods.htm", section: "Documentation Apex> System > Pattern", isExternal: true},
  {label: "Class Queueable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Queueable.htm", section: "Documentation Apex> System > Queueable", isExternal: true},
  {label: "Class QueueableContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_system_queueablecontext.htm", section: "Documentation Apex> System > QueueableContext", isExternal: true},
  {label: "Class QueueableDuplicateSignature", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_QueueableDuplicateSignature.htm", section: "Documentation Apex> System > QueueableDuplicateSignature", isExternal: true},
  {label: "Class QuickAction", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_quickaction.htm", section: "Documentation Apex> System > QuickAction", isExternal: true},
  {label: "Class RemoteObjectController", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_remoteobjectcontroller.htm", section: "Documentation Apex> System > RemoteObjectController", isExternal: true},
  {label: "Class Request", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm", section: "Documentation Apex> System > Request", isExternal: true},
  {label: "Class ResetPasswordResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_ResetPasswordResult.htm", section: "Documentation Apex> System > ResetPasswordResult", isExternal: true},
  {label: "Class RestContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_restcontext.htm", section: "Documentation Apex> System > RestContext", isExternal: true},
  {label: "Class RestRequest", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_restrequest.htm", section: "Documentation Apex> System > RestRequest", isExternal: true},
  {label: "Class RestResponse", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_restresponse.htm", section: "Documentation Apex> System > RestResponse", isExternal: true},
  {label: "Class SandboxPostCopy", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_SandboxPostCopy.htm", section: "Documentation Apex> System > SandboxPostCopy", isExternal: true},
  {label: "Class Schedulable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_system_schedulable.htm", section: "Documentation Apex> System > Schedulable", isExternal: true},
  {label: "Class SchedulableContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_system_schedulablecontext.htm", section: "Documentation Apex> System > SchedulableContext", isExternal: true},
  {label: "Class Schema", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_schema.htm", section: "Documentation Apex> System > Schema", isExternal: true},
  {label: "Class Search", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_search.htm", section: "Documentation Apex> System > Search", isExternal: true},
  {label: "Class Security", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Security.htm", section: "Documentation Apex> System > Security", isExternal: true},
  {label: "Class SelectOption", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_pages_selectoption.htm", section: "Documentation Apex> System > SelectOption", isExternal: true},
  {label: "Class Set", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_set.htm", section: "Documentation Apex> System > Set", isExternal: true},
  {label: "Class Site", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_sites.htm", section: "Documentation Apex> System > Site", isExternal: true},
  {label: "Class SObject", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_sobject.htm", section: "Documentation Apex> System > SObject", isExternal: true},
  {label: "Class SObjectAccessDecision", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_SObjectAccessDecision.htm", section: "Documentation Apex> System > SObjectAccessDecision", isExternal: true},
  {label: "Class StaticResourceCalloutMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_staticresourcecalloutmock.htm", section: "Documentation Apex> System > StaticResourceCalloutMock", isExternal: true},
  {label: "Class String", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_string.htm", section: "Documentation Apex> System > String", isExternal: true},
  {label: "Class StubProvider", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_StubProvider.htm", section: "Documentation Apex> System > StubProvider", isExternal: true},
  {label: "Class System", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_system.htm", section: "Documentation Apex> System > System", isExternal: true},
  {label: "Class Test", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_test.htm", section: "Documentation Apex> System > Test", isExternal: true},
  {label: "Class Time", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_time.htm", section: "Documentation Apex> System > Time", isExternal: true},
  {label: "Class TimeZone", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_timezone.htm", section: "Documentation Apex> System > TimeZone", isExternal: true},
  {label: "Class Type", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_type.htm", section: "Documentation Apex> System > Type", isExternal: true},
  {label: "Class UninstallHandler", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_uninstall_handler.htm", section: "Documentation Apex> System > UninstallHandler", isExternal: true},
  {label: "Class URL", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_url.htm", section: "Documentation Apex> System > URL", isExternal: true},
  {label: "Class UserInfo", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_userinfo.htm", section: "Documentation Apex> System > UserInfo", isExternal: true},
  {label: "Class UserManagement", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_UserManagement.htm", section: "Documentation Apex> System > UserManagement", isExternal: true},
  {label: "Class Version", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_version.htm", section: "Documentation Apex> System > Version", isExternal: true},
  {label: "Class WebServiceCallout", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_WebServiceCallout.htm", section: "Documentation Apex> System > WebServiceCallout", isExternal: true},
  {label: "Class WebServiceMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_webservicemock.htm", section: "Documentation Apex> System > WebServiceMock", isExternal: true},
  {label: "Class XmlStreamReader", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_xml_XmlStream_reader.htm", section: "Documentation Apex> System > XmlStreamReader", isExternal: true},
  {label: "Class XmlStreamWriter", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_xml_XmlStream_writer.htm", section: "Documentation Apex> System > XmlStreamWriter", isExternal: true},
  {label: "Class Boolean", link: "", section: "Documentation Apex> System > String", isExternal: true}
]);
